uploads = []
outputs = []

[[generated]]
id = "gvm5XYgxcD8FBO0md2obr"
uri = "file://artifacts/birthday-love/src/assets/solo-1.png"
type = "image"
title = "Woman silhouette at golden hour"

[[generated]]
id = "57InXFQCzwSjmpWRZKc6f"
uri = "file://artifacts/birthday-love/src/assets/solo-2.png"
type = "image"
title = "Woman smiling in soft light"

[[generated]]
id = "AUZ4CMaLwqaUkDXvi8p_Y"
uri = "file://artifacts/birthday-love/src/assets/solo-3.png"
type = "image"
title = "Woman in field of flowers"

[[generated]]
id = "S3cvU3MbObe397w_Lp_54"
uri = "file://artifacts/birthday-love/src/assets/couple-1.png"
type = "image"
title = "Couple holding hands walking"

[[generated]]
id = "aPFzNMFvLO9Uk4kqlyh_i"
uri = "file://artifacts/birthday-love/src/assets/couple-2.png"
type = "image"
title = "Couple silhouetted against sky"

[[generated]]
id = "dYKE3lbUOYGJP_SdEpDoo"
uri = "file://artifacts/birthday-love/src/assets/couple-3.png"
type = "image"
title = "Close up couple holding hands"

[[generated]]
id = "nT8yuWQAUr2ELqxo-4cFy"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-hug.png"
type = "image"
title = "panda couple hugging"

[[generated]]
id = "XLv9pLEk_rURKl1E5FjPD"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-heart.png"
type = "image"
title = "panda offering giant heart"

[[generated]]
id = "Gcezyu2vLUj0edcd6ZhTq"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-cake.png"
type = "image"
title = "pandas sharing cake"

[[generated]]
id = "3AK9pxys3ci7kkAWwVq1C"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-kiss.png"
type = "image"
title = "panda kissing cheek"

[[generated]]
id = "VBJtjw2XhoOBOflgIR24s"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-sleep.png"
type = "image"
title = "pandas sleeping blanket"

[[generated]]
id = "tiVA6dc-QibUGtHbqYChq"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-flowers.png"
type = "image"
title = "panda offering flowers"

[[generated]]
id = "8gmsu-KY50hymL0KXMMeL"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-walk.png"
type = "image"
title = "pandas holding hands"

[[generated]]
id = "gNGhjA6FBuQbdlNsYxUnp"
uri = "file://artifacts/birthday-love/src/assets/stickers/panda-backhug.png"
type = "image"
title = "panda back hug"

[[generated]]
id = "qE-vq4giwi4Bf8659NzS1"
uri = "file://artifacts/birthday-love/src/assets/intro-cake.png"
type = "image"
title = "generated_image"
